#include "main.h"
#include "PID_Def.h"
#include "Mode_Def.h"
#include "system.h"

/*
* 功能：系统初始化
*/
void System_Init(void)
{
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_4);//设置系统中断优先级分组 4
 
	/*GPIO初始化*/ 
	LED_Init();                   //板载LED初始化
  Laser_Init();                 //激光初始化
	Yaw_Zero_GPIO_Init();         //Y轴中值光电初始化 PA3
  Yaw_Two_Zero_GPIO_Init();     //副Y轴中值光电初始化 PA2	
	Cap_OUT_IO_Init();            //电容放电开关板初始化 PA2
	 
	/*CAN通信初始化*/
	CAN1_Configuration(CAN_SJW_1tq, CAN_BS1_8tq, CAN_BS2_5tq, 3, CAN_Mode_Normal);         //can1初始化
  CAN2_Configuration(CAN_SJW_1tq, CAN_BS1_8tq, CAN_BS2_5tq, 3, CAN_Mode_Normal);         //can2板间通信初始化
	
	/*串口初始化*/ 
	Usart1_Init();          	    //串口一初始化（底遥控）
	Usart2_Init();                //串口二初始化（云陀螺，底功率）
  Usart3_Init();                //串口三初始化（云MiniPC）		
  Usart6_Init();                //串口六初始化（底裁判/云陀螺）
		  
	/*PWM初始化*/ 
	TIM4_PWM_Init(2111-1,84-1);                //摩擦轮初始化             
		TIM4->CCR1=1000;                            
		TIM4->CCR2=1000;                                
  TIM3_PWM_Init(2000-1,840-1);                  //弹仓盖 & 副云台P 舵机初始
		TIM3->CCR1=0;                             //弹仓盖初始位置 & 副云台P初始化
		TIM3->CCR2=0;                             //电容充电控制初始0-200

	/*参数初始化*/
	PID_Parameter_Init();    
	
  /*副云台初始化*/	
  #ifdef double_gimbal
	#endif
	
  /*看门狗初始化*/
  #ifdef watch_dog
   IWDG_Init();
	#endif  
	
	
 /*初始化完成状态*/
  LEDB7=1;
	Laser_ON();                       //打开激光
			 
}



/*
* 功能：PID参数初始化
* 备注：结构体定义在rmmotor文件
*/
void PID_Parameter_Init(void)
{ 
	/*************底盘电机位置环**************/
	CHASSIS_1_P_PID.kp=CHASSIS_P_1_P;
	CHASSIS_1_P_PID.ki=CHASSIS_P_1_I;
	CHASSIS_1_P_PID.kd=CHASSIS_P_1_D;
	CHASSIS_1_P_PID.Error=0;
	CHASSIS_1_P_PID.iError=0;
	CHASSIS_1_P_PID.LastError=0;
	CHASSIS_1_P_PID.outputValue_Int32=0;
	CHASSIS_1_P_PID.PrevError=0;
	CHASSIS_1_P_PID.SetValue=0;
	
	CHASSIS_2_P_PID.kp=CHASSIS_P_2_P;
	CHASSIS_2_P_PID.ki=CHASSIS_P_2_I;
	CHASSIS_2_P_PID.kd=CHASSIS_P_2_D;
	CHASSIS_2_P_PID.Error=0;
	CHASSIS_2_P_PID.iError=0;
	CHASSIS_2_P_PID.LastError=0;
	CHASSIS_2_P_PID.outputValue_Int32=0;
	CHASSIS_2_P_PID.PrevError=0;
	CHASSIS_2_P_PID.SetValue=0;
	
	CHASSIS_3_P_PID.kp=CHASSIS_P_3_P;
	CHASSIS_3_P_PID.ki=CHASSIS_P_3_I;
	CHASSIS_3_P_PID.kd=CHASSIS_P_3_D;
	CHASSIS_3_P_PID.Error=0;
	CHASSIS_3_P_PID.iError=0;
	CHASSIS_3_P_PID.LastError=0;
	CHASSIS_3_P_PID.outputValue_Int32=0;
	CHASSIS_3_P_PID.PrevError=0;
	CHASSIS_3_P_PID.SetValue=0;
	
	CHASSIS_4_P_PID.kp=CHASSIS_P_4_P;
	CHASSIS_4_P_PID.ki=CHASSIS_P_4_I;
	CHASSIS_4_P_PID.kd=CHASSIS_P_4_D;
	CHASSIS_4_P_PID.Error=0;
	CHASSIS_4_P_PID.iError=0;
	CHASSIS_4_P_PID.LastError=0;
	CHASSIS_4_P_PID.outputValue_Int32=0;
	CHASSIS_4_P_PID.PrevError=0;
	CHASSIS_4_P_PID.SetValue=0;
	
	/*************底盘电机速度环**************/
	CHASSIS_1_S_PID.kp=CHASSIS_S_1_P;
	CHASSIS_1_S_PID.ki=CHASSIS_S_1_I;
	CHASSIS_1_S_PID.kd=CHASSIS_S_1_D;
	CHASSIS_1_S_PID.Error=0;
	CHASSIS_1_S_PID.iError=0;
	CHASSIS_1_S_PID.LastError=0;
	CHASSIS_1_S_PID.outputValue_Int32=0;
	CHASSIS_1_S_PID.PrevError=0;
	CHASSIS_1_S_PID.SetValue=0;
	
	CHASSIS_2_S_PID.kp=CHASSIS_S_2_P;
	CHASSIS_2_S_PID.ki=CHASSIS_S_2_I;
	CHASSIS_2_S_PID.kd=CHASSIS_S_2_D;
	CHASSIS_2_S_PID.Error=0;
	CHASSIS_2_S_PID.iError=0;
	CHASSIS_2_S_PID.LastError=0;
	CHASSIS_2_S_PID.outputValue_Int32=0;
	CHASSIS_2_S_PID.PrevError=0;
	CHASSIS_2_S_PID.SetValue=0;
	
	CHASSIS_3_S_PID.kp=CHASSIS_S_3_P;
	CHASSIS_3_S_PID.ki=CHASSIS_S_3_I;
	CHASSIS_3_S_PID.kd=CHASSIS_S_3_D;
	CHASSIS_3_S_PID.Error=0;
	CHASSIS_3_S_PID.iError=0;
	CHASSIS_3_S_PID.LastError=0;
	CHASSIS_3_S_PID.outputValue_Int32=0;
	CHASSIS_3_S_PID.PrevError=0;
	CHASSIS_3_S_PID.SetValue=0;
	
	CHASSIS_4_S_PID.kp=CHASSIS_S_4_P;
	CHASSIS_4_S_PID.ki=CHASSIS_S_4_I;
	CHASSIS_4_S_PID.kd=CHASSIS_S_4_D;
	CHASSIS_4_S_PID.Error=0;
	CHASSIS_4_S_PID.iError=0;
	CHASSIS_4_S_PID.LastError=0;
	CHASSIS_4_S_PID.outputValue_Int32=0;
	CHASSIS_4_S_PID.PrevError=0;
	CHASSIS_4_S_PID.SetValue=0;
	
	CHASSIS_MOVE_FOLLOW_PID.kp=CHASSIS_MOVE_FOLLOW_P;
	CHASSIS_MOVE_FOLLOW_PID.ki=CHASSIS_MOVE_FOLLOW_I;
	CHASSIS_MOVE_FOLLOW_PID.kd=CHASSIS_MOVE_FOLLOW_D;
	CHASSIS_MOVE_FOLLOW_PID.Error=0;
	CHASSIS_MOVE_FOLLOW_PID.iError=0;
	CHASSIS_MOVE_FOLLOW_PID.LastError=0;
	CHASSIS_MOVE_FOLLOW_PID.PrevError=0;
	CHASSIS_MOVE_FOLLOW_PID.OutputValue=0;
	CHASSIS_MOVE_FOLLOW_PID.outputValue_Int32=0;
	CHASSIS_MOVE_FOLLOW_PID.LastOutput=0;
	CHASSIS_MOVE_FOLLOW_PID.SetValue=0;

	CHASSIS_ROTATE_FOLLOW_PID.kp=CHASSIS_ROTATE_FOLLOW_P;
	CHASSIS_ROTATE_FOLLOW_PID.ki=CHASSIS_ROTATE_FOLLOW_I;
	CHASSIS_ROTATE_FOLLOW_PID.kd=CHASSIS_ROTATE_FOLLOW_D;
	CHASSIS_ROTATE_FOLLOW_PID.Error=0;
	CHASSIS_ROTATE_FOLLOW_PID.iError=0;
	CHASSIS_ROTATE_FOLLOW_PID.LastError=0;
	CHASSIS_ROTATE_FOLLOW_PID.PrevError=0;
	CHASSIS_ROTATE_FOLLOW_PID.OutputValue=0;
	CHASSIS_ROTATE_FOLLOW_PID.outputValue_Int32=0;
	CHASSIS_ROTATE_FOLLOW_PID.LastOutput=0;
	CHASSIS_ROTATE_FOLLOW_PID.SetValue=0;
	
	/*******供弹电机速度环初始化*******/
	FIRE_S_PID.kp=FIRE_S_P;
	FIRE_S_PID.ki=FIRE_S_I;
	FIRE_S_PID.kd=FIRE_S_D;
	FIRE_S_PID.Error=0;
	FIRE_S_PID.iError=0;	
	FIRE_S_PID.LastError=0;
	FIRE_S_PID.outputValue_Int32=0;
	FIRE_S_PID.PrevError=0;
	FIRE_S_PID.SetValue=0;
	
	/***********云台PY参数初始化*************/
	//Pitch
	GIMBAL_P_PITCH_PID.kp=GIMBAL_P_PITCH_P; 
	GIMBAL_P_PITCH_PID.ki=GIMBAL_P_PITCH_I;
	GIMBAL_P_PITCH_PID.kd=GIMBAL_P_PITCH_D;
	GIMBAL_P_PITCH_PID.Error=0;
	GIMBAL_P_PITCH_PID.iError=0;
	GIMBAL_P_PITCH_PID.LastError=0;
	GIMBAL_P_PITCH_PID.OutputValue=0;
	GIMBAL_P_PITCH_PID.outputValue_Int32=0;
	GIMBAL_P_PITCH_PID.LastOutput=0;
	GIMBAL_P_PITCH_PID.SetValue=0;
	
	GIMBAL_S_PITCH_PID.kp=GIMBAL_S_PITCH_P;
	GIMBAL_S_PITCH_PID.ki=GIMBAL_S_PITCH_I;
	GIMBAL_S_PITCH_PID.kd=GIMBAL_S_PITCH_D;
	GIMBAL_S_PITCH_PID.Error=0;
	GIMBAL_S_PITCH_PID.iError=0;	
	GIMBAL_S_PITCH_PID.LastError=0;
	GIMBAL_S_PITCH_PID.PrevError=0;
	GIMBAL_S_PITCH_PID.OutputValue=0;
	GIMBAL_S_PITCH_PID.outputValue_Int32=0;
	GIMBAL_S_PITCH_PID.LastOutput=0;
	GIMBAL_S_PITCH_PID.SetValue=0;
	
	//Yaw
	GIMBAL_P_YAW_PID.kp=GIMBAL_P_YAW_P;
	GIMBAL_P_YAW_PID.ki=GIMBAL_P_YAW_I;
	GIMBAL_P_YAW_PID.kd=GIMBAL_P_YAW_D;
	GIMBAL_P_YAW_PID.Error=0;
	GIMBAL_P_YAW_PID.iError=0;	
	GIMBAL_P_YAW_PID.LastError=0; 
	GIMBAL_P_YAW_PID.OutputValue=0;
	GIMBAL_P_YAW_PID.outputValue_Int32=0;
	GIMBAL_P_YAW_PID.LastOutput=0;
	GIMBAL_P_YAW_PID.SetValue=0;
	
	GIMBAL_S_YAW_PID.kp=GIMBAL_S_YAW_P;
	GIMBAL_S_YAW_PID.ki=GIMBAL_S_YAW_I;
	GIMBAL_S_YAW_PID.kd=GIMBAL_S_YAW_D;
	GIMBAL_S_YAW_PID.Error=0;
	GIMBAL_S_YAW_PID.iError=0;
	GIMBAL_S_YAW_PID.LastError=0;
	GIMBAL_S_YAW_PID.PrevError=0;
	GIMBAL_S_YAW_PID.OutputValue=0;
	GIMBAL_S_YAW_PID.outputValue_Int32=0;
	GIMBAL_S_YAW_PID.LastOutput=0;
	GIMBAL_S_YAW_PID.SetValue=0;

	
	//Independent_Yaw
	GIMBAL_INDEPENDENT_P_YAW_PID.kp=GIMBAL_INDEPENDENT_P_YAW_P;
	GIMBAL_INDEPENDENT_P_YAW_PID.ki=GIMBAL_INDEPENDENT_P_YAW_I;
	GIMBAL_INDEPENDENT_P_YAW_PID.kd=GIMBAL_INDEPENDENT_P_YAW_D;
	GIMBAL_INDEPENDENT_P_YAW_PID.Error=0;
	GIMBAL_INDEPENDENT_P_YAW_PID.iError=0;	
	GIMBAL_INDEPENDENT_P_YAW_PID.LastError=0; 
	GIMBAL_INDEPENDENT_P_YAW_PID.OutputValue=0;
	GIMBAL_INDEPENDENT_P_YAW_PID.outputValue_Int32=0;
	GIMBAL_INDEPENDENT_P_YAW_PID.LastOutput=0;
	GIMBAL_INDEPENDENT_P_YAW_PID.SetValue=0;
	
	GIMBAL_INDEPENDENT_S_YAW_PID.kp=GIMBAL_INDEPENDENT_S_YAW_P;
	GIMBAL_INDEPENDENT_S_YAW_PID.ki=GIMBAL_INDEPENDENT_S_YAW_I;
	GIMBAL_INDEPENDENT_S_YAW_PID.kd=GIMBAL_INDEPENDENT_S_YAW_D;
	GIMBAL_INDEPENDENT_S_YAW_PID.Error=0;
	GIMBAL_INDEPENDENT_S_YAW_PID.iError=0;
	GIMBAL_INDEPENDENT_S_YAW_PID.LastError=0;
	GIMBAL_INDEPENDENT_S_YAW_PID.PrevError=0;
	GIMBAL_INDEPENDENT_S_YAW_PID.OutputValue=0;
	GIMBAL_INDEPENDENT_S_YAW_PID.outputValue_Int32=0;
	GIMBAL_INDEPENDENT_S_YAW_PID.LastOutput=0;
	GIMBAL_INDEPENDENT_S_YAW_PID.SetValue=0;
	
  //打符模式pid   P轴
  GIMBAL_AUTO_BUFF_P_PITCH_PID.kp=GIMBAL_AUTO_BUFF_P_PITCH_P;
	GIMBAL_AUTO_BUFF_P_PITCH_PID.ki=GIMBAL_AUTO_BUFF_P_PITCH_I;
	GIMBAL_AUTO_BUFF_P_PITCH_PID.kd=GIMBAL_AUTO_BUFF_P_PITCH_D;
	GIMBAL_AUTO_BUFF_P_PITCH_PID.Error=0;
	GIMBAL_AUTO_BUFF_P_PITCH_PID.iError=0;
	GIMBAL_AUTO_BUFF_P_PITCH_PID.LastError=0;
	GIMBAL_AUTO_BUFF_P_PITCH_PID.OutputValue=0;
	GIMBAL_AUTO_BUFF_P_PITCH_PID.outputValue_Int32=0;
	GIMBAL_AUTO_BUFF_P_PITCH_PID.LastOutput=0;
	GIMBAL_AUTO_BUFF_P_PITCH_PID.SetValue=0;
	
	GIMBAL_AUTO_BUFF_S_PITCH_PID.kp=GIMBAL_AUTO_BUFF_S_PITCH_P;
	GIMBAL_AUTO_BUFF_S_PITCH_PID.ki=GIMBAL_AUTO_BUFF_S_PITCH_I;
	GIMBAL_AUTO_BUFF_S_PITCH_PID.kd=GIMBAL_AUTO_BUFF_S_PITCH_D;
	GIMBAL_AUTO_BUFF_S_PITCH_PID.Error=0;
	GIMBAL_AUTO_BUFF_S_PITCH_PID.iError=0;	
	GIMBAL_AUTO_BUFF_S_PITCH_PID.LastError=0;
	GIMBAL_AUTO_BUFF_S_PITCH_PID.PrevError=0;
	GIMBAL_AUTO_BUFF_S_PITCH_PID.OutputValue=0;
	GIMBAL_AUTO_BUFF_S_PITCH_PID.outputValue_Int32=0;
	GIMBAL_AUTO_BUFF_S_PITCH_PID.LastOutput=0;
	GIMBAL_AUTO_BUFF_S_PITCH_PID.SetValue=0;
	
	//打符模式pid    Y轴
	GIMBAL_AUTO_BUFF_P_YAW_PID.kp=GIMBAL_AUTO_BUFF_P_YAW_P;
	GIMBAL_AUTO_BUFF_P_YAW_PID.ki=GIMBAL_AUTO_BUFF_P_YAW_I;
	GIMBAL_AUTO_BUFF_P_YAW_PID.kd=GIMBAL_AUTO_BUFF_P_YAW_D;
	GIMBAL_AUTO_BUFF_P_YAW_PID.Error=0;
	GIMBAL_AUTO_BUFF_P_YAW_PID.iError=0;	
	GIMBAL_AUTO_BUFF_P_YAW_PID.LastError=0;
	GIMBAL_AUTO_BUFF_P_YAW_PID.OutputValue=0;
	GIMBAL_AUTO_BUFF_P_YAW_PID.outputValue_Int32=0;
	GIMBAL_AUTO_BUFF_P_YAW_PID.LastOutput=0;
	GIMBAL_AUTO_BUFF_P_YAW_PID.SetValue=0;
	
	GIMBAL_AUTO_BUFF_S_YAW_PID.kp=GIMBAL_AUTO_BUFF_S_YAW_P;
	GIMBAL_AUTO_BUFF_S_YAW_PID.ki=GIMBAL_AUTO_BUFF_S_YAW_I;
	GIMBAL_AUTO_BUFF_S_YAW_PID.kd=GIMBAL_AUTO_BUFF_S_YAW_D;
	GIMBAL_AUTO_BUFF_S_YAW_PID.Error=0;
	GIMBAL_AUTO_BUFF_S_YAW_PID.iError=0;
	GIMBAL_AUTO_BUFF_S_YAW_PID.LastError=0;
	GIMBAL_AUTO_BUFF_S_YAW_PID.PrevError=0;
	GIMBAL_AUTO_BUFF_S_YAW_PID.OutputValue=0;
	GIMBAL_AUTO_BUFF_S_YAW_PID.outputValue_Int32=0;
	GIMBAL_AUTO_BUFF_S_YAW_PID.LastOutput=0;
	GIMBAL_AUTO_BUFF_S_YAW_PID.SetValue=0;
	
 if(test_short_focus)
 {
  //Auto_Pitch
  GIMBAL_AUTO_P_PITCH_PID.kp=GIMBAL_AUTO_SHORT_P_PITCH_P;
	GIMBAL_AUTO_P_PITCH_PID.ki=GIMBAL_AUTO_SHORT_P_PITCH_I;
	GIMBAL_AUTO_P_PITCH_PID.kd=GIMBAL_AUTO_SHORT_P_PITCH_D;
	GIMBAL_AUTO_P_PITCH_PID.Error=0;
	GIMBAL_AUTO_P_PITCH_PID.iError=0;
	GIMBAL_AUTO_P_PITCH_PID.LastError=0;
	GIMBAL_AUTO_P_PITCH_PID.OutputValue=0;
	GIMBAL_AUTO_P_PITCH_PID.outputValue_Int32=0;
	GIMBAL_AUTO_P_PITCH_PID.LastOutput=0;
	GIMBAL_AUTO_P_PITCH_PID.SetValue=0;
	
	GIMBAL_AUTO_S_PITCH_PID.kp=GIMBAL_AUTO_SHORT_S_PITCH_P;
	GIMBAL_AUTO_S_PITCH_PID.ki=GIMBAL_AUTO_SHORT_S_PITCH_I;
	GIMBAL_AUTO_S_PITCH_PID.kd=GIMBAL_AUTO_SHORT_S_PITCH_D;
	GIMBAL_AUTO_S_PITCH_PID.Error=0;
	GIMBAL_AUTO_S_PITCH_PID.iError=0;	
	GIMBAL_AUTO_S_PITCH_PID.LastError=0;
	GIMBAL_AUTO_S_PITCH_PID.PrevError=0;
	GIMBAL_AUTO_S_PITCH_PID.OutputValue=0;
	GIMBAL_AUTO_S_PITCH_PID.outputValue_Int32=0;
	GIMBAL_AUTO_S_PITCH_PID.LastOutput=0;
	GIMBAL_AUTO_S_PITCH_PID.SetValue=0;
	
	//Auto_Yaw
	GIMBAL_AUTO_P_YAW_PID.kp=GIMBAL_AUTO_SHORT_P_YAW_P;
	GIMBAL_AUTO_P_YAW_PID.ki=GIMBAL_AUTO_SHORT_P_YAW_I;
	GIMBAL_AUTO_P_YAW_PID.kd=GIMBAL_AUTO_SHORT_P_YAW_D;
	GIMBAL_AUTO_P_YAW_PID.Error=0;
	GIMBAL_AUTO_P_YAW_PID.iError=0;	
	GIMBAL_AUTO_P_YAW_PID.LastError=0;
	GIMBAL_AUTO_P_YAW_PID.OutputValue=0;
	GIMBAL_AUTO_P_YAW_PID.outputValue_Int32=0;
	GIMBAL_AUTO_P_YAW_PID.LastOutput=0;
	GIMBAL_AUTO_P_YAW_PID.SetValue=0;
	
	GIMBAL_AUTO_S_YAW_PID.kp=GIMBAL_AUTO_SHORT_S_YAW_P;
	GIMBAL_AUTO_S_YAW_PID.ki=GIMBAL_AUTO_SHORT_S_YAW_I;
	GIMBAL_AUTO_S_YAW_PID.kd=GIMBAL_AUTO_SHORT_S_YAW_D;
	GIMBAL_AUTO_S_YAW_PID.Error=0;
	GIMBAL_AUTO_S_YAW_PID.iError=0;
	GIMBAL_AUTO_S_YAW_PID.LastError=0;
	GIMBAL_AUTO_S_YAW_PID.PrevError=0;
	GIMBAL_AUTO_S_YAW_PID.OutputValue=0;
	GIMBAL_AUTO_S_YAW_PID.outputValue_Int32=0;
	GIMBAL_AUTO_S_YAW_PID.LastOutput=0;
	GIMBAL_AUTO_S_YAW_PID.SetValue=0;
  }
  else if(test_long_focus)
	{
  //Auto_Pitch
  GIMBAL_AUTO_P_PITCH_PID.kp=GIMBAL_AUTO_LONG_P_PITCH_P;
	GIMBAL_AUTO_P_PITCH_PID.ki=GIMBAL_AUTO_LONG_P_PITCH_I;
	GIMBAL_AUTO_P_PITCH_PID.kd=GIMBAL_AUTO_LONG_P_PITCH_D;
	GIMBAL_AUTO_P_PITCH_PID.Error=0;
	GIMBAL_AUTO_P_PITCH_PID.iError=0;
	GIMBAL_AUTO_P_PITCH_PID.LastError=0;
	GIMBAL_AUTO_P_PITCH_PID.OutputValue=0;
	GIMBAL_AUTO_P_PITCH_PID.outputValue_Int32=0;
	GIMBAL_AUTO_P_PITCH_PID.LastOutput=0;
	GIMBAL_AUTO_P_PITCH_PID.SetValue=0;
	
	GIMBAL_AUTO_S_PITCH_PID.kp=GIMBAL_AUTO_LONG_S_PITCH_P;
	GIMBAL_AUTO_S_PITCH_PID.ki=GIMBAL_AUTO_LONG_S_PITCH_I;
	GIMBAL_AUTO_S_PITCH_PID.kd=GIMBAL_AUTO_LONG_S_PITCH_D;
	GIMBAL_AUTO_S_PITCH_PID.Error=0;
	GIMBAL_AUTO_S_PITCH_PID.iError=0;	
	GIMBAL_AUTO_S_PITCH_PID.LastError=0;
	GIMBAL_AUTO_S_PITCH_PID.PrevError=0;
	GIMBAL_AUTO_S_PITCH_PID.OutputValue=0;
	GIMBAL_AUTO_S_PITCH_PID.outputValue_Int32=0;
	GIMBAL_AUTO_S_PITCH_PID.LastOutput=0;
	GIMBAL_AUTO_S_PITCH_PID.SetValue=0;
	
	//Auto_Yaw
	GIMBAL_AUTO_P_YAW_PID.kp=GIMBAL_AUTO_LONG_P_YAW_P;
	GIMBAL_AUTO_P_YAW_PID.ki=GIMBAL_AUTO_LONG_P_YAW_I;
	GIMBAL_AUTO_P_YAW_PID.kd=GIMBAL_AUTO_LONG_P_YAW_D;
	GIMBAL_AUTO_P_YAW_PID.Error=0;
	GIMBAL_AUTO_P_YAW_PID.iError=0;	
	GIMBAL_AUTO_P_YAW_PID.LastError=0;
	GIMBAL_AUTO_P_YAW_PID.OutputValue=0;
	GIMBAL_AUTO_P_YAW_PID.outputValue_Int32=0;
	GIMBAL_AUTO_P_YAW_PID.LastOutput=0;
	GIMBAL_AUTO_P_YAW_PID.SetValue=0;
	
	GIMBAL_AUTO_S_YAW_PID.kp=GIMBAL_AUTO_LONG_S_YAW_P;
	GIMBAL_AUTO_S_YAW_PID.ki=GIMBAL_AUTO_LONG_S_YAW_I;
	GIMBAL_AUTO_S_YAW_PID.kd=GIMBAL_AUTO_LONG_S_YAW_D;
	GIMBAL_AUTO_S_YAW_PID.Error=0;
	GIMBAL_AUTO_S_YAW_PID.iError=0;
	GIMBAL_AUTO_S_YAW_PID.LastError=0;
	GIMBAL_AUTO_S_YAW_PID.PrevError=0;
	GIMBAL_AUTO_S_YAW_PID.OutputValue=0;
	GIMBAL_AUTO_S_YAW_PID.outputValue_Int32=0;
	GIMBAL_AUTO_S_YAW_PID.LastOutput=0;
	GIMBAL_AUTO_S_YAW_PID.SetValue=0;
  }
	else if(test_industry)
	{
  //Auto_Pitch
  GIMBAL_AUTO_P_PITCH_PID.kp=GIMBAL_AUTO_INDUSTRY_P_PITCH_P;
	GIMBAL_AUTO_P_PITCH_PID.ki=GIMBAL_AUTO_INDUSTRY_P_PITCH_I;
	GIMBAL_AUTO_P_PITCH_PID.kd=GIMBAL_AUTO_INDUSTRY_P_PITCH_D;
	GIMBAL_AUTO_P_PITCH_PID.Error=0;
	GIMBAL_AUTO_P_PITCH_PID.iError=0;
	GIMBAL_AUTO_P_PITCH_PID.LastError=0;
	GIMBAL_AUTO_P_PITCH_PID.OutputValue=0;
	GIMBAL_AUTO_P_PITCH_PID.outputValue_Int32=0;
	GIMBAL_AUTO_P_PITCH_PID.LastOutput=0;
	GIMBAL_AUTO_P_PITCH_PID.SetValue=0;
	
	GIMBAL_AUTO_S_PITCH_PID.kp=GIMBAL_AUTO_INDUSTRY_S_PITCH_P;
	GIMBAL_AUTO_S_PITCH_PID.ki=GIMBAL_AUTO_INDUSTRY_S_PITCH_I;
	GIMBAL_AUTO_S_PITCH_PID.kd=GIMBAL_AUTO_INDUSTRY_S_PITCH_D;
	GIMBAL_AUTO_S_PITCH_PID.Error=0;
	GIMBAL_AUTO_S_PITCH_PID.iError=0;	
	GIMBAL_AUTO_S_PITCH_PID.LastError=0;
	GIMBAL_AUTO_S_PITCH_PID.PrevError=0;
	GIMBAL_AUTO_S_PITCH_PID.OutputValue=0;
	GIMBAL_AUTO_S_PITCH_PID.outputValue_Int32=0;
	GIMBAL_AUTO_S_PITCH_PID.LastOutput=0;
	GIMBAL_AUTO_S_PITCH_PID.SetValue=0;
	
	//Auto_Yaw
	GIMBAL_AUTO_P_YAW_PID.kp=GIMBAL_AUTO_INDUSTRY_P_YAW_P;
	GIMBAL_AUTO_P_YAW_PID.ki=GIMBAL_AUTO_INDUSTRY_P_YAW_I;
	GIMBAL_AUTO_P_YAW_PID.kd=GIMBAL_AUTO_INDUSTRY_P_YAW_D;
	GIMBAL_AUTO_P_YAW_PID.Error=0;
	GIMBAL_AUTO_P_YAW_PID.iError=0;	
	GIMBAL_AUTO_P_YAW_PID.LastError=0;
	GIMBAL_AUTO_P_YAW_PID.OutputValue=0;
	GIMBAL_AUTO_P_YAW_PID.outputValue_Int32=0;
	GIMBAL_AUTO_P_YAW_PID.LastOutput=0;
	GIMBAL_AUTO_P_YAW_PID.SetValue=0;
	
	GIMBAL_AUTO_S_YAW_PID.kp=GIMBAL_AUTO_INDUSTRY_S_YAW_P;
	GIMBAL_AUTO_S_YAW_PID.ki=GIMBAL_AUTO_INDUSTRY_S_YAW_I;
	GIMBAL_AUTO_S_YAW_PID.kd=GIMBAL_AUTO_INDUSTRY_S_YAW_D;
	GIMBAL_AUTO_S_YAW_PID.Error=0;
	GIMBAL_AUTO_S_YAW_PID.iError=0;
	GIMBAL_AUTO_S_YAW_PID.LastError=0;
	GIMBAL_AUTO_S_YAW_PID.PrevError=0;
	GIMBAL_AUTO_S_YAW_PID.OutputValue=0;
	GIMBAL_AUTO_S_YAW_PID.outputValue_Int32=0;
	GIMBAL_AUTO_S_YAW_PID.LastOutput=0;
	GIMBAL_AUTO_S_YAW_PID.SetValue=0;		
	}

	 
	//Second Pitch
	GIMBAL_DOUBLE_P_PITCH_PID.kp=GIMBAL_DOUBLE_P_PITCH_P; 
	GIMBAL_DOUBLE_P_PITCH_PID.ki=GIMBAL_DOUBLE_P_PITCH_I;
	GIMBAL_DOUBLE_P_PITCH_PID.kd=GIMBAL_DOUBLE_P_PITCH_D;
	GIMBAL_DOUBLE_P_PITCH_PID.Error=0;
	GIMBAL_DOUBLE_P_PITCH_PID.iError=0;
	GIMBAL_DOUBLE_P_PITCH_PID.LastError=0;
	GIMBAL_DOUBLE_P_PITCH_PID.OutputValue=0;
	GIMBAL_DOUBLE_P_PITCH_PID.outputValue_Int32=0;
	GIMBAL_DOUBLE_P_PITCH_PID.LastOutput=0;
	GIMBAL_DOUBLE_P_PITCH_PID.SetValue=0;
	
	GIMBAL_DOUBLE_S_PITCH_PID.kp=GIMBAL_DOUBLE_S_PITCH_P;
	GIMBAL_DOUBLE_S_PITCH_PID.ki=GIMBAL_DOUBLE_S_PITCH_I;
	GIMBAL_DOUBLE_S_PITCH_PID.kd=GIMBAL_DOUBLE_S_PITCH_D;
	GIMBAL_DOUBLE_S_PITCH_PID.Error=0;
	GIMBAL_DOUBLE_S_PITCH_PID.iError=0;	
	GIMBAL_DOUBLE_S_PITCH_PID.LastError=0;
	GIMBAL_DOUBLE_S_PITCH_PID.PrevError=0;
	GIMBAL_DOUBLE_S_PITCH_PID.OutputValue=0;
	GIMBAL_DOUBLE_S_PITCH_PID.outputValue_Int32=0;
	GIMBAL_DOUBLE_S_PITCH_PID.LastOutput=0;
	GIMBAL_DOUBLE_S_PITCH_PID.SetValue=0;
	
	//Second Yaw
	GIMBAL_DOUBLE_P_YAW_PID.kp=GIMBAL_DOUBLE_P_YAW_P;
	GIMBAL_DOUBLE_P_YAW_PID.ki=GIMBAL_DOUBLE_P_YAW_I;
	GIMBAL_DOUBLE_P_YAW_PID.kd=GIMBAL_DOUBLE_P_YAW_D;
	GIMBAL_DOUBLE_P_YAW_PID.Error=0;
	GIMBAL_DOUBLE_P_YAW_PID.iError=0;	
	GIMBAL_DOUBLE_P_YAW_PID.LastError=0; 
	GIMBAL_DOUBLE_P_YAW_PID.OutputValue=0;
	GIMBAL_DOUBLE_P_YAW_PID.outputValue_Int32=0;
	GIMBAL_DOUBLE_P_YAW_PID.LastOutput=0;
	GIMBAL_DOUBLE_P_YAW_PID.SetValue=0;
	
	GIMBAL_DOUBLE_S_YAW_PID.kp=GIMBAL_DOUBLE_S_YAW_P;
	GIMBAL_DOUBLE_S_YAW_PID.ki=GIMBAL_DOUBLE_S_YAW_I;
	GIMBAL_DOUBLE_S_YAW_PID.kd=GIMBAL_DOUBLE_S_YAW_D;
	GIMBAL_DOUBLE_S_YAW_PID.Error=0;
	GIMBAL_DOUBLE_S_YAW_PID.iError=0;
	GIMBAL_DOUBLE_S_YAW_PID.LastError=0;
	GIMBAL_DOUBLE_S_YAW_PID.PrevError=0;
	GIMBAL_DOUBLE_S_YAW_PID.OutputValue=0;
	GIMBAL_DOUBLE_S_YAW_PID.outputValue_Int32=0;
	GIMBAL_DOUBLE_S_YAW_PID.LastOutput=0;
	GIMBAL_DOUBLE_S_YAW_PID.SetValue=0;
	
}
